// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmcerwmiwoovzbcycspn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtY2Vyd21pd29vdnpiY3ljc3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzE3NTgsImV4cCI6MjA2MjQ0Nzc1OH0.Cec_Y_2xhebL3M3GFaOBirMnRDSv-lVpVDwa8o6U_uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);